### ISSUE TITLE
Documentation or Enhancement : extend functions

### ISSUE THREAD

**Issue by StephaneTy-Pro** [CDSoft/ypp#2]
Could you explain if possible how to extend ypp ; by example i need a include which eliminate blocks export of jsfile ,

If this is not possible without monkeypatch will it be possible to add the ability to extend ypp with custom functions

By the way
Thanks for all the works you do on ypp and luax

**Comment by CDSoft** [comment]
Not sure to understand your needs. Could you please give a concrete example?

ypp is based on a Lua interpreter and you can import any Lua module with `require` or the `-l` command line option. E.g.:

module.lua:
``` lua
function reverse(s)
    return string.reverse(s)
end
```

load module.lua from the command line:
```
ypp -l module.lua
```
and use it:
```
@reverse "abc"            <- should output "cba"
```

or load module.lua directly from the document:

```
@require "module"

@reverse "abc"
```

But keep in mind that ypp can only transform text that is given to macros as arguments.

**Comment by StephaneTy-Pro** [comment]
what i need for this sample

------- any js file ----

some code

const fn1 = function() ...
const fn2 = function() ...
....

export { fn1, fn2 }


when i want to use this file i would include anything with @include  or @include.raw except the exports

what i have try out is clone your include function, with some modification

and modifiy the metatable, save it to a file monkeypatch.lua  and use ypp -l monkeypatch.lua

but no success (probably because not directly accessible)

**Comment by CDSoft** [comment]
Ok, that's clear.

The `include` function can be told to include only a part of the file by providing a pattern but it can not exclude parts of the file. I can add an attribute to also exclude portions of the file.

Anyway this can be done after having included the file (but the excluded portions are preprocessed and may have unwanted side effects). E.g.:

Define a function:
``` lua
function remove_export(s)
    return s:gsub("export%s*%b{}", "")
end
```

and apply it to the included file:
```
@remove_export(include "file.js")
```

or even:
```
@include "file.js" : gsub("export%s*%b{}", "")
```

**Comment by CDSoft** [comment]
or
``` lua
function include_js(filename)
    return include(filename) : gsub("export%s*%b{}", "")
end
```

and just use `include_js` instead of `include`

```
@include_js "file.js"
```

**Comment by CDSoft** [comment]
In the latest version, `include` has an `exclude` attribute to remove parts of the included file. `exclude` is a Lua pattern. E.g.:
```
@include "file.js" { exclude="export%s*%b{}" }
```
